version: "3.8"
services:

  db:
    build: ./database
    volumes:
      - epitechmoulibot-volume:/var/lib/mysql/data
    networks:
      - epitechmoulibotNetwork
    environment:
      MYSQL_DATABASE: 'epitechmoulibot'
      MYSQL_USER: ${DATABASE_USER}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}
    restart: on-failure

  api-database:
    build: ./api-db
    networks:
      - epitechmoulibotNetwork
    environment:
      MYSQL_DATABASE: 'epitechmoulibot'
      MYSQL_HOST: 'db'
      MYSQL_USER: ${DATABASE_USER}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}
      HOST_NAME: 'api-database'
      SECRET: ${API_SECRET}
      OTHER_APP_TOKEN: ${API_DB_TOKEN}
      PORT: ${API_DB_PORT}
    ports:
      - "${API_DB_PORT}:${API_DB_PORT}"
    depends_on:
      - db
    restart: on-failure

  my-epitech-relay:
    build: ./my-epitech-relay
    networks:
      - epitechmoulibotNetwork
    environment:
      API_DB_HOST: ${API_DB_COMPLET}
      HOST_NAME: 'my-epitech-relay'
      API_DB_TOKEN: ${API_DB_TOKEN}
      PORT: ${RELAY_PORT}
      BROWSER_BINARY_PATH: ${RELAY_BROWSER_BINARY_PATH}
      BROWSER_TYPE: ${RELAY_BROWSER_TYPE}
      BROWSER_ARGS: '--no-sandbox'
      NO_WINDOW: 1
    ports:
      - "${RELAY_PORT}:${RELAY_PORT}"
    depends_on:
      - db
      - api-database
    restart: on-failure

  discord-bot:
    build: ./discord-bot
    networks:
      - epitechmoulibotNetwork
    environment:
      API_DB_HOST: ${API_DB_COMPLET}
      API_DB_TOKEN: ${API_DB_TOKEN}
      DEV_DISCORD_BOT_TOKEN: ${DISCORD_BOT_DEV_TOKEN}
      FINAL_DISCORD_BOT_TOKEN: ${DISCORD_BOT_FINAL_TOKEN}
      WEBHOOK_URL: ${DISCORD_WEBHOOK_URL}
      RELAY_HOST: ${RELAY_API}
    depends_on:
      - db
      - api-database
      - my-epitech-relay
    restart: on-failure

networks:
  epitechmoulibotNetwork:
    driver: host

volumes:
  epitechmoulibot-volume: