version: "3.8"
services:
  db:
    build: ./database
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    restart: always
  api-database:
    build: ./api-database
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_HOST: ${MYSQL_HOST}
      SECRET: ${SECRET}
      OTHER_APP_TOKEN: ${OTHER_APP_TOKEN}
      PORT: ${PORT}
    ports:
      - "${PORT}:${PORT}"
    depends_on:
      - db
    restart: on-failure
