version: "3.8"
services:

  db:
    image: 'redboard/epitechmoulibot:database'
    container_name: 'epitechmoulibot-database'
    volumes:
      - epitechmoulibot-volume:/var/lib/mysql
    networks:
      epitechmoulibotNetwork:
        ipv4_address: 12.7.1.1
    environment:
      MYSQL_DATABASE: 'epitechmoulibot'
      MYSQL_USER: ${DATABASE_USER}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}
    restart: on-failure

  api-database:
    image: 'redboard/epitechmoulibot:api-db'
    container_name: 'epitechmoulibot-api-db'
    networks:
      epitechmoulibotNetwork:
        ipv4_address: 12.7.1.2
    environment:
      MYSQL_DATABASE: 'epitechmoulibot'
      MYSQL_HOST: 'db'
      MYSQL_USER: ${DATABASE_USER}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}
      HOST_NAME: 'api-database'
      SECRET: ${API_SECRET}
      OTHER_APP_TOKEN: ${API_DB_TOKEN}
      PORT: ${API_DB_PORT}
    ports:
      - "${API_DB_PORT}:${API_DB_PORT}"
    depends_on:
      - db
    restart: on-failure

  relay:
    image: 'redboard/epitechmoulibot:my-epitech-relay'
    container_name: 'epitechmoulibot-relay'
    networks:
      epitechmoulibotNetwork:
        ipv4_address: 12.7.1.3
    environment:
      API_DB_HOST: ${API_DB_COMPLET}
      HOST_NAME: 'relay'
      API_DB_TOKEN: ${API_DB_TOKEN}
      PORT: ${RELAY_PORT}
      BROWSER_BINARY_PATH: ${RELAY_BROWSER_BINARY_PATH}
      BROWSER_TYPE: ${RELAY_BROWSER_TYPE}
      BROWSER_ARGS: '--no-sandbox'
      NO_WINDOW: 1
    ports:
      - "${RELAY_PORT}:${RELAY_PORT}"
    depends_on:
      - db
      - api-database
    restart: on-failure

  discord-bot:
    image: 'redboard/epitechmoulibot:discord-bot'
    container_name: 'epitechmoulibot-discord-bot'
    networks:
      epitechmoulibotNetwork:
        ipv4_address: 12.7.1.4
    environment:
      API_DB_HOST: ${API_DB_COMPLET}
      API_DB_TOKEN: ${API_DB_TOKEN}
      DEV_DISCORD_BOT_TOKEN: ${DISCORD_BOT_DEV_TOKEN}
      FINAL_DISCORD_BOT_TOKEN: ${DISCORD_BOT_FINAL_TOKEN}
      WEBHOOK_URL: ${DISCORD_WEBHOOK_URL}
      RELAY_HOST: ${RELAY_API}
    depends_on:
      - db
      - api-database
      - relay
    restart: on-failure

networks:
  epitechmoulibotNetwork:
    driver: bridge
    ipam:
      config:
        - subnet: 12.7.0.0/16
          gateway: 12.7.0.1

volumes:
  epitechmoulibot-volume:
