version: "3.9"
services:
  db:
    build: ./database
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    restart: on-failure

  api-database:
    build: ./api-database
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_HOST: ${API_DB_HOST}
      SECRET: ${SECRET}
      OTHER_APP_TOKEN: ${API_DB_TOKEN}
      PORT: ${API_DB_PORT}
    ports:
      - "${API_DB_PORT}:${API_DB_PORT}"
    depends_on:
      - db
    restart: on-failure

  my-epitech-relay:
    build: ./my-epitech-relay
    environment:
      API_DB_HOST: ${RELAY_API_DB_HOST}
      HOST_NAME: ${RELAY_HOST}
      API_DB_TOKEN: ${API_DB_TOKEN}
      PORT: ${RELAY_PORT}
      BROWSER_BINARY_PATH: "/usr/bin/chromium"
    ports:
      - "${RELAY_PORT}:${RELAY_PORT}"
    depends_on:
      - db
      - api-database
    restart: on-failure


  discord-bots:
    build: ./discord-bot
    environment:
      API_DB_HOST: ${RELAY_API_DB_HOST}
      API_DB_TOKEN: ${API_DB_TOKEN}
      DEV_DISCORD_BOT_TOKEN: ${DEV_DISCORD_BOT_TOKEN}
      FINAL_DISCORD_BOT_TOKEN: ${FINAL_DISCORD_BOT_TOKEN}
      WEBHOOK_URL: ${WEBHOOK_URL}
      RELAY_HOST: ${RELAY_API}
    # ports:
      # - "${RELAY_PORT}:${RELAY_PORT}"
    depends_on:
      - db
      - api-database
      - my-epitech-relay
    restart: on-failure
